// SPDX-License-Identifier: Apache-2.0
package chiselasync.metadata

import chiselasync.core.AsyncModule
import circt.stage.ChiselStage
import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.{Files, Path}
import java.security.MessageDigest
import scala.jdk.CollectionConverters._

/** Read-probe export. check_export.py must validate the resulting RTL before consumption. */
object ExportDesign {
  sealed trait Mode { def options: Seq[String] }
  private val lowering = Vector("--strip-fir-debug-info", "--lowering-options=disallowPortDeclSharing,disallowLocalVariables")
  case object Optimized extends Mode { def options = Vector("-O=release") ++ lowering }
  case object Debug extends Mode { def options = Vector("-O=debug", "--no-dedup", "--preserve-values=named") ++ lowering }
  def options: Seq[String] = Optimized.options
  private def sha(bytes: Array[Byte]): String = MessageDigest.getInstance("SHA-256").digest(bytes)
    .map(b => f"${b & 0xff}%02x").mkString

  // Retain the original three-argument JVM entry point for compiled consumers.
  def emit(gen: => AsyncModule, destination: Path, mode: Mode = Optimized): Unit =
    emit(gen, destination, mode, qualifiedOnly = false)

  def emit(gen: => AsyncModule, destination: Path, qualifiedOnly: Boolean): Unit =
    emit(gen, destination, Optimized, qualifiedOnly)

  def emit(gen: => AsyncModule, destination: Path, mode: Mode, qualifiedOnly: Boolean): Unit = {
    Files.createDirectories(destination)
    Files.deleteIfExists(destination.resolve("contract.json"))
    Files.deleteIfExists(destination.resolve("resolved.json"))
    val chiselVersion = chisel3.BuildInfo.version
    val scalaVersion = scala.util.Properties.versionNumberString
    def qualification(condition: Boolean, message: String): Unit = if (!condition) {
      require(!qualifiedOnly, message)
      System.err.println(s"chisel-async warning: $message; export is not qualified by the pinned regression corpus")
    }
    qualification(chiselVersion == "7.16.0" && scalaVersion == "2.13.18",
      s"unqualified runtime: Chisel $chiselVersion, Scala $scalaVersion")
    var module: AsyncModule = null
    ChiselStage.emitSystemVerilogFile({ module = gen; module },
      Array("--target-dir", destination.toAbsolutePath.toString),
      mode.options.toArray ++ Array(s"--output-hw-mlir=${destination.toAbsolutePath.resolve("design.hw.mlir")}"))
    val contract = module.contract.json
    def resources(node: ujson.Value): Seq[String] = node("primitives").arr.map(_("resource").str).toSeq ++
      node("children").arr.flatMap(child => resources(child("contract")))
    val hashes = resources(contract).distinct.sorted.map { name =>
      val stream = Option(getClass.getResourceAsStream(s"/$name"))
        .getOrElse(throw new IllegalArgumentException(s"missing behavioral resource: $name"))
      val bytes = try stream.readAllBytes() finally stream.close()
      name -> ujson.Str(sha((new String(bytes, UTF_8).replace("\r\n", "\n").stripTrailing() + "\n").getBytes(UTF_8)))
    }
    val compilerVersions = scala.collection.mutable.Set.empty[String]
    val rtlHashes = Files.readAllLines(destination.resolve("filelist.f"), UTF_8).asScala
      .filter(_.trim.nonEmpty).map { relative =>
        val path = destination.resolve(relative.trim.replace('\\', '/')).normalize()
        val lines = Files.readAllLines(path, UTF_8).asScala
        val header = "// Generated by CIRCT firtool-"
        require(lines.headOption.exists(_.startsWith(header)), "missing firtool provenance header")
        compilerVersions += lines.head.stripPrefix(header)
        val normalized = lines.map(_.split("\t//", 2)(0).stripTrailing())
          .mkString("\n").stripTrailing() + "\n"
        path.getFileName.toString -> ujson.Str(sha(normalized.getBytes(UTF_8)))
      }.sortBy(_._1)
    require(compilerVersions.size == 1, "inconsistent firtool output provenance")
    val firtoolVersion = compilerVersions.head
    qualification(firtoolVersion == "1.160.0", s"unqualified firtool $firtoolVersion")
    val probeFile = s"ref_${module.name}.sv"
    val probeHash = sha(Files.readString(destination.resolve(probeFile), UTF_8).replace("\r\n", "\n").getBytes(UTF_8))
    val portFile = "ports.json"
    val portText = ujson.write(ujson.Obj("schema" -> "chisel-async-port-abi-v2", "top" -> module.name,
      "nodes" -> ujson.Arr.from(module.contract.portAbi)), indent = 2) + "\n"
    Files.writeString(destination.resolve(portFile), portText, UTF_8)
    val manifest = ujson.Obj("schema" -> "chisel-async-contract-v3", "time_unit" -> "fs",
      "time_range" -> "0..9223372036854775807", "top" -> module.name,
      "toolchain" -> ujson.Obj("chisel" -> chiselVersion, "scala" -> scalaVersion, "firtool" -> firtoolVersion,
        "options" -> ujson.Arr.from(mode.options)), "resources" -> ujson.Obj.from(hashes),
      "rtl_semantic_sha256" -> ujson.Obj.from(rtlHashes),
      "probe_abi" -> ujson.Obj("file" -> probeFile, "sha256" -> probeHash),
      "port_abi" -> ujson.Obj("file" -> portFile, "sha256" -> sha(portText.getBytes(UTF_8))), "design" -> contract)
    // Hash compact insertion-ordered JSON. No filesystem paths or timestamps enter this identity.
    val semantic = ujson.write(manifest)
    val result = ujson.Obj("semantic_sha256" -> sha(semantic.getBytes(UTF_8)), "manifest" -> manifest)
    Files.writeString(destination.resolve("contract.json"), ujson.write(result, indent = 2) + "\n", UTF_8)
  }
}
