// SPDX-License-Identifier: Apache-2.0
package chiselasync.metadata

import chiselasync.core.AsyncModule
import circt.stage.ChiselStage
import java.nio.charset.StandardCharsets.UTF_8
import java.nio.file.{Files, Path}
import java.security.MessageDigest
import scala.jdk.CollectionConverters._

/** Qualified debug export. check_export.py must validate the resulting RTL before consumption. */
object ExportDesign {
  val options: Seq[String] = Vector("-O=debug", "--no-dedup", "--preserve-values=named",
    "--strip-fir-debug-info", "--lowering-options=disallowPortDeclSharing,disallowLocalVariables")
  private def sha(bytes: Array[Byte]): String = MessageDigest.getInstance("SHA-256").digest(bytes)
    .map(b => f"${b & 0xff}%02x").mkString

  def emit(gen: => AsyncModule, destination: Path): Unit = {
    Files.createDirectories(destination)
    Files.deleteIfExists(destination.resolve("contract.json"))
    Files.deleteIfExists(destination.resolve("resolved.json"))
    val chiselVersion = chisel3.BuildInfo.version
    val scalaVersion = scala.util.Properties.versionNumberString
    require(chiselVersion == "7.16.0" && scalaVersion == "2.13.18",
      s"unqualified runtime: Chisel $chiselVersion, Scala $scalaVersion")
    var module: AsyncModule = null
    ChiselStage.emitSystemVerilogFile({ module = gen; module },
      Array("--target-dir", destination.toAbsolutePath.toString),
      options.toArray ++ Array(s"--output-hw-mlir=${destination.toAbsolutePath.resolve("design.hw.mlir")}"))
    val contract = module.contract.json
    def resources(node: ujson.Value): Seq[String] = node("primitives").arr.map(_("resource").str).toSeq ++
      node("children").arr.flatMap(child => resources(child("contract")))
    val hashes = resources(contract).distinct.sorted.map { name =>
      val stream = Option(getClass.getResourceAsStream(s"/$name"))
        .getOrElse(throw new IllegalArgumentException(s"missing behavioral resource: $name"))
      val bytes = try stream.readAllBytes() finally stream.close()
      name -> ujson.Str(sha((new String(bytes, UTF_8).replace("\r\n", "\n").stripTrailing() + "\n").getBytes(UTF_8)))
    }
    val rtlHashes = Files.readAllLines(destination.resolve("filelist.f"), UTF_8).asScala
      .filter(_.trim.nonEmpty).map { relative =>
        val path = destination.resolve(relative.trim.replace('\\', '/')).normalize()
        val lines = Files.readAllLines(path, UTF_8).asScala
        require(lines.headOption.contains("// Generated by CIRCT firtool-1.160.0"), "unqualified firtool output")
        val normalized = lines.map(_.split("\t//", 2)(0).stripTrailing())
          .mkString("\n").stripTrailing() + "\n"
        path.getFileName.toString -> ujson.Str(sha(normalized.getBytes(UTF_8)))
      }.sortBy(_._1)
    val manifest = ujson.Obj("schema" -> "chisel-async-contract-v1", "time_unit" -> "fs",
      "time_range" -> "0..9223372036854775807", "top" -> module.name,
      "toolchain" -> ujson.Obj("chisel" -> chiselVersion, "scala" -> scalaVersion, "firtool" -> "1.160.0",
        "options" -> ujson.Arr.from(options)), "resources" -> ujson.Obj.from(hashes),
      "rtl_semantic_sha256" -> ujson.Obj.from(rtlHashes), "design" -> contract)
    // Hash compact insertion-ordered JSON. No filesystem paths or timestamps enter this identity.
    val semantic = ujson.write(manifest)
    val result = ujson.Obj("semantic_sha256" -> sha(semantic.getBytes(UTF_8)), "manifest" -> manifest)
    Files.writeString(destination.resolve("contract.json"), ujson.write(result, indent = 2) + "\n", UTF_8)
  }
}
